services:
  backend-1:
    image: gabxdevv/rinha-backend-2025-java-gabxdev-unix-final:1.0.0
    restart: always
    volumes:
      - /tmp:/tmp
    environment:
      RETRY_API_DEFAULT: 8
      WORKER_POOL_SIZE: 16
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      UDP_CHANNEL_INTERNAL_PORT: 9003
      EXTERNAL_UDP_HOST: backend-2
      EXTERNAL_UDP_PORT: 9004
      API_UDP_PORT: 9095
      API_MASTER: true
      LB_UDP_HOST: load-balance
      SOCKET_PATH: /tmp/api1-1.sock
      SOCKET_PATH_2: /tmp/api1-2.sock
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.575'
          memory: '135MB'

  backend-2:
    image: gabxdevv/rinha-backend-2025-java-gabxdev-unix-final:1.0.0
    restart: always
    volumes:
      - /tmp:/tmp
    environment:
      RETRY_API_DEFAULT: 8
      WORKER_POOL_SIZE: 16
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      UDP_CHANNEL_INTERNAL_PORT: 9004
      EXTERNAL_UDP_HOST: backend-1
      EXTERNAL_UDP_PORT: 9003
      SOCKET_PATH: /tmp/api2-1.sock
      SOCKET_PATH_2: /tmp/api2-2.sock
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.575'
          memory: '135MB'

  load-balance:
    image: gabxdevv/load-balance-java-gabxdev-unix-final:1.0.0
    restart: always
    volumes:
      - /tmp:/tmp
    depends_on:
      - backend-1
      - backend-2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "80MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true