services:
  backend-1:
    image: gabxdevv/rinha-backend-2025-java-gabxdev-undertow-unix:1.0.0
    restart: always
    environment:
      RETRY_API_DEFAULT: 15
      WORKER_POOL_SIZE: 16
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      UDP_CHANNEL_INTERNAL_PORT: 9003
      EXTERNAL_UDP_HOST: backend-2
      SERVER_PORT: 8080
      EXTERNAL_UDP_PORT: 9004
      CLIENT_BACKOFF: 250
      WORKERS_THREAD_POOL_SIZE: 8
      IO_THREAD_POOL_SIZE: 3
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '125MB'

  backend-2:
    image: gabxdevv/rinha-backend-2025-java-gabxdev-undertow-unix:1.0.0
    restart: always
    environment:
      RETRY_API_DEFAULT: 15
      WORKER_POOL_SIZE: 16
      URL_PROCESSOR_DEFAULT: http://payment-processor-default:8080/payments
      URL_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080/payments
      UDP_CHANNEL_INTERNAL_PORT: 9004
      EXTERNAL_UDP_HOST: backend-1
      EXTERNAL_UDP_PORT: 9003
      SERVER_PORT: 8080
      CLIENT_BACKOFF: 250
      WORKERS_THREAD_POOL_SIZE: 8
      IO_THREAD_POOL_SIZE: 3
      JAVA_OPTS: >-
        -server
        -XX:+UseG1GC
        -XX:+UseFastAccessorMethods
        -Xlog:disable
        -XX:-PrintGC
        -XX:+UseStringCache
        -XX:-PrintGCDetails
        -XX:-FlightRecorder
        -XX:+DisableExplicitGC
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '125MB'

  load-balancer:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-1
      - backend-2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true